//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulateTheWorld.GUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locals_German {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locals_German() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulateTheWorld.GUI.Resources.Localization.Locals_German", typeof(Locals_German).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Länder ähnelt.
        /// </summary>
        public static string mapfilters_countries {
            get {
                return ResourceManager.GetString("mapfilters_countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Höhe ähnelt.
        /// </summary>
        public static string mapfilters_height {
            get {
                return ResourceManager.GetString("mapfilters_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lebensstandard ähnelt.
        /// </summary>
        public static string mapfilters_lifeStandard {
            get {
                return ResourceManager.GetString("mapfilters_lifeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewohner nach Stamm ähnelt.
        /// </summary>
        public static string mapfilters_popByTribe {
            get {
                return ResourceManager.GetString("mapfilters_popByTribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kohle ähnelt.
        /// </summary>
        public static string mapfilters_ressource_coal {
            get {
                return ResourceManager.GetString("mapfilters_ressource_coal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erdgas ähnelt.
        /// </summary>
        public static string mapfilters_ressource_Gas {
            get {
                return ResourceManager.GetString("mapfilters_ressource_Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Golderz ähnelt.
        /// </summary>
        public static string mapfilters_ressource_goldOre {
            get {
                return ResourceManager.GetString("mapfilters_ressource_goldOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eisenerz ähnelt.
        /// </summary>
        public static string mapfilters_ressource_ironOre {
            get {
                return ResourceManager.GetString("mapfilters_ressource_ironOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erdöl ähnelt.
        /// </summary>
        public static string mapfilters_ressource_Oil {
            get {
                return ResourceManager.GetString("mapfilters_ressource_Oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Urbanisierung ähnelt.
        /// </summary>
        public static string mapfilters_urbanization {
            get {
                return ResourceManager.GetString("mapfilters_urbanization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vegetations-Zonen ähnelt.
        /// </summary>
        public static string mapfilters_vegetationZone {
            get {
                return ResourceManager.GetString("mapfilters_vegetationZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kartenfilter ähnelt.
        /// </summary>
        public static string sidepanel_expander_mapFilters {
            get {
                return ResourceManager.GetString("sidepanel_expander_mapFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angepinnte Orte ähnelt.
        /// </summary>
        public static string sidepanel_expander_pinnedLocations {
            get {
                return ResourceManager.GetString("sidepanel_expander_pinnedLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        public static string sidepanel_expander_search {
            get {
                return ResourceManager.GetString("sidepanel_expander_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        public static string sidepanel_search {
            get {
                return ResourceManager.GetString("sidepanel_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string toolbar_close {
            get {
                return ResourceManager.GetString("toolbar_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeiten ähnelt.
        /// </summary>
        public static string toolbar_edit {
            get {
                return ResourceManager.GetString("toolbar_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        public static string toolbar_file {
            get {
                return ResourceManager.GetString("toolbar_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string toolbar_help {
            get {
                return ResourceManager.GetString("toolbar_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnen ähnelt.
        /// </summary>
        public static string toolbar_open {
            get {
                return ResourceManager.GetString("toolbar_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        public static string toolbar_view {
            get {
                return ResourceManager.GetString("toolbar_view", resourceCulture);
            }
        }
    }
}
